### ISSUE TITLE
Headline looks good at xs & s but floats left in M & L

### ISSUE THREAD

**Issue by sydneyselch** [sydneyselch/dsn1675-saas#1]
The headline "any-song, any-where, any-time" is centered and looks okay at extra small and small but at medium and large it appears to float feft and not stay centered. Just past 715px the grey box does not span across. 

I want the grey box behind the paragraph to span all the way across like the billboard does at all sizes and the text to stay centered at all sizes. I want the text to be centered but not get larger when it reaches the largest media query. 

I don't believe it is a media query issue — it just needs to be set in the css for every size to span the grey box apart and make it centered at all sizes. 

Line 36-40 in HTML

This is the css for the paragraph over the billboard

``` css
.calltoaction {
    bottom: 0;
    padding: 0.9rem;
    margin: 0 1rem 0;
    position: absolute;
    background-color: rgba(0,0,0,0.3);
    color: #fff;
    font-size: 2.5rem;
    line-height: 2.5rem;
    font-family: "Avant Garde", Avantgarde, "Century Gothic", CenturyGothic, "AppleGothic", sans-serif;
    text-align: center;
    overflow: hidden;
}
```
